version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    ports:
      - '5432:5432'

  web:
    build:
      context: .
    restart: always
    container_name: api_container
    ports:
      - '8000:8000'
    env_file:
      - ./Kursova/.env
    depends_on:
      - postgres

volumes:
  postgres_data:
